name: dock
channels:
  - conda-forge
  - defaults
  - bioconda
dependencies:
  - python~=3.11
  - rdkit
  - openjdk=17
  - meeko
  - pdbfixer
  - ProDy
  - py3dmol
  - numpy
  - pandas
  - requests
  - streamlit
  - molscrub 
  - multiprocess
  - chemicalite
  - reduce