#!/usr/bin/env python3
import argparse
import shutil
import subprocess
import re
import os
from pathlib import Path


def resolve_path(path_value: str, repo_root: Path) -> Path:
    path = Path(path_value)
    return path.resolve()

def run_command(command: list[str], log_path: Path) -> None:
    log_path.parent.mkdir(parents=True, exist_ok=True)
    with log_path.open("w") as handle:
        completed = subprocess.run(command, stdout=handle, stderr=subprocess.STDOUT, check=False)
    if completed.returncode != 0:
        raise subprocess.CalledProcessError(completed.returncode, command)

def main() -> None:
    parser = argparse.ArgumentParser(description="Dock ligands into discretized tunnels generated by the tunnel computation script")
    parser.add_argument("--tunnel_results_dir", default="../output/tunnel_results", help="Directory containing tunnel computation outputs. Expected structure: .../tunnel_results_dir/<protein_id>/<pocket_id>/data/tunnel_<tunnel_idx>.dsd")
    parser.add_argument("--ligand_dir", default="../data/prepared_ligands", help="Folder with prepared ligand PDBQT files")
    parser.add_argument("--prep_receptor_dir", default="../data/docking_files/filtered_receptors", help="Folder with prepared receptor PDBQT files")
    parser.add_argument("--output_dir", type=str, default="../output/tunnel_results", help='Output root dir. Results will be stored in <output_dir>/<protein_id>/<pocket_dir>/docking_tunnel_<tunnel_id>/<ligand>/')
    parser.add_argument("--exhaustiveness", type=int, default=8, help="CAVER docking exhaustiveness")
    parser.add_argument("--mpi_procs", type=int, default=15, help="Number of MPI processes for caverdock")
    parser.add_argument("--seed", type=int, default=42, help="Random seed for docking")
    parser.add_argument("--cd_image", type=str, default="../caverdock-1.2.sif", help="Path to CaverDock Apptainer image")
    args = parser.parse_args()

    repo_root = Path(__file__).resolve().parents[1]
    tunnel_results_dir = resolve_path(args.tunnel_results_dir, repo_root)
    ligand_dir = resolve_path(args.ligand_dir, repo_root)
    prep_receptor_dir = resolve_path(args.prep_receptor_dir, repo_root)
    cd_image_path = resolve_path(args.cd_image, repo_root)

    if not tunnel_results_dir.exists():
        raise FileNotFoundError(f"Tunnel results directory not found: {tunnel_results_dir}")
    if not ligand_dir.exists():
        raise FileNotFoundError(f"Ligand directory not found: {ligand_dir}")
    if not prep_receptor_dir.exists():
        raise FileNotFoundError(f"Prepared receptor directory not found: {prep_receptor_dir}")

    pocket_id_regex = re.compile(r'(\d+)$')

    for discr_tunnel in sorted(tunnel_results_dir.rglob("*.dsd")):
        pocket_dir = discr_tunnel.parent.parent
        pocket_id = pocket_id_regex.search(pocket_dir.stem).group()
        prot_name = pocket_dir.parent.name
        tunnel_idx = discr_tunnel.stem.removesuffix('.dsd').split('_')[-1]
        pocket_name = pocket_dir.name
        dock_base_dir = Path(args.output_dir) / prot_name / pocket_dir

        prep_receptor = prep_receptor_dir / prot_name / f"{prot_name}_H_p{pocket_id}.pdbqt"
        if not prep_receptor.exists():
            print(f"Skipping {prot_name} {pocket_name} tunnel {tunnel_idx}: receptor file not found at {prep_receptor}")
            continue

        print(f"--- Docking into {prot_name} {pocket_name} tunnel {tunnel_idx} ---")
        for ligand_path in sorted(ligand_dir.glob("*.pdbqt")):
            ligand_name = ligand_path.stem
            dock_out_dir = dock_base_dir / f"docking_tunnel_{tunnel_idx}"/ ligand_name
            dock_out_dir.mkdir(parents=True, exist_ok=True)
            result_file = dock_out_dir / f"{ligand_name}_tunnel{tunnel_idx}-ub.pdbqt"
            if result_file.exists():
                print(f"Skipping already completed: {ligand_name} into {prot_name} {pocket_name} tunnel {tunnel_idx}")
                continue

            dock_conf = dock_out_dir / f"cd_tunnel{tunnel_idx}.conf"
            prepare_conf_command = [
                "apptainer", "exec",  str(cd_image_path), 
                "cd-prepareconf",
                "-r",
                str(prep_receptor),
                "-l",
                str(ligand_path),
                "-t",
                str(discr_tunnel),
                "--seed",
                str(args.seed),
                "--exhaustiveness",
                str(args.exhaustiveness)
            ]
            run_command(prepare_conf_command, dock_conf.with_suffix(".log"))
            shutil.copy2(dock_conf.with_suffix(".log"), dock_conf)

            # The prepare-conf command writes the docking configuration to stdout,
            # so the log file is also copied to the config path for the downstream tool.
            if not dock_conf.exists():
                raise AssertionError(f"Docking configuration was not written for {ligand_name}")
  
            output_prefix = dock_out_dir / f"{ligand_name}_tunnel{tunnel_idx}"
            caverdock_command = [
                "caverdock",
                "--config",
                str(dock_conf),
                "--out",
                str(output_prefix),
            ]
            if args.mpi_procs > 1:
                caverdock_command = ["mpirun.openmpi", "-v", "--use-hwthread-cpus"] + caverdock_command + ["--parallel_workers_lb",
                str(args.mpi_procs // 2)]

            run_command(["apptainer", "exec",  str(cd_image_path) ] + caverdock_command, dock_out_dir / "log.txt")

            energy_dat = dock_out_dir / f"tunnel{tunnel_idx}_energy_profile.dat"
            energy_pdf = dock_out_dir / f"tunnel{tunnel_idx}_energy_profile.png"
            energy_command = ["cd-energyprofile", "-d", str(discr_tunnel), "-t", str(result_file), "-s", "0"]
            run_command(["apptainer", "exec",  str(cd_image_path) ] + energy_command, energy_dat.with_suffix(".log"))
            shutil.copy2(energy_dat.with_suffix(".log"), energy_dat)
            if shutil.which("gnuplot"):
                gnuplot_script = (
                    f"set terminal png; set output '{energy_pdf}'; set xlabel 'distance'; set ylabel 'energy'; "
                    f"plot '{energy_dat}' u 1:4 w l t 'upper-bound', '' u 1:6 w l t 'lower-bound'"
                )
                subprocess.run(["gnuplot", "-e", gnuplot_script], check=False)
            else:
                print(f"gnuplot not found; skipping energy profile image for {ligand_name}")

if __name__ == "__main__":
    main()
